name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  release-pypi:
    name: release-pypi
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Build
        run: |
          pip install build
          python -m build
      - name: Upload to Pypi
        run: |
          pip install twine
          twine upload --username __token__ --password ${{ secrets.PYPI_TOKEN }} dist/*
